services:
  db:
    image: postgres:16
    container_name: chess_teacher_postgres
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


    env_file: # TODO: only provide necessary vars
      - ../.env

    volumes:
      - ../storage/postgres:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT}:5432"

  app:
    build: ..
    container_name: chess_teacher_app

    depends_on:
      - db

    env_file:
      - ../.env

    volumes:
      - ../storage/raw:/app/storage/raw

    ports:
      - "${APP_PORT}:8501"
