from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from chess_teacher.utils.table_data_class import TableDataClass


@dataclass(frozen=True)
class RawGame(TableDataClass):
    game_id: str
    platform_game_id: str
    account_id: str
    raw_response: str
    source_file: str
    ingested_at: datetime

    @classmethod
    def get_yaml_path(cls) -> Path:
        return Path(__file__).parent / "metadata.yml"

    @classmethod
    def get_key(cls) -> str:
        return "raw_games"

    @classmethod
    def get_id_hash_columns(cls) -> tuple[str, ...]:
        """
        PK is generated by hashing account_id and platform_game_id.
        Design choice to use account_id: White and black players will load the same game
        under a different PK to differentiate between proponent and opponent perspectives.
        Note that the platform is unique per account, so does not need to be included.
        """
        return ("account_id", "platform_game_id")
