from dataclasses import dataclass
from pathlib import Path

from chess_teacher.utils.table_data_class import TableDataClass


@dataclass(frozen=True)
class RawGame(TableDataClass):
    @classmethod
    def get_yaml_path(cls) -> Path:
        return Path(__file__).parent / "metadata.yml"

    @classmethod
    def get_key(cls) -> str:
        return "raw_games"

    @classmethod
    def get_id_hash_columns(cls) -> tuple[str, ...]:
        """
        PK is generated by hashing account_id and platform_game_id.
        Design choice to use account_id: White and black players will load the same game
        under a different PK to differentiate between proponent and opponent perspectives.
        Note that the platform is unique per account, so does not need to be included.
        """
        return ("account_id", "platform_game_id")

    # @classmethod
    # def get_timestamp_columns(cls) -> tuple[str, ...]:
    #     return ("created_at",)

    # @classmethod
    # def get_dataclass_field_names(cls) -> set[str]:
    #     return {"id", "created_at", "updated_at"}
