services:
  streamlit: # For streamlit app: use --profile streamlit when running docker-compose
    image: ${DOCKERHUB_USERNAME}/chess_teacher:develop
    build: {}
    pull_policy: always
    environment:
      ENVIRONMENT: DEV

  nightly-job:
    image: ${DOCKERHUB_USERNAME}/chess_teacher:develop
    build: {}
    pull_policy: always

    depends_on:
      db:
        condition: service_healthy

    env_file: # could be cleaner in future (only provide necessary vars)
      - ../../.env
    environment: #override local ENVIRONMENT value
      ENVIRONMENT: DEV

    volumes:
      - ../../storage/raw:/app/storage/raw

    command: python scripts/maintenance.py
