[client]
showSidebarNavigation = false

[theme]
base = "light"

[theme.light]
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#262730"
primaryColor = "#3F51B5"

[theme.dark]
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
primaryColor = "#7C8CFF"
